name: pr_type

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

jobs:
  check_pull_request_type:
    name: Check for PR kind
    runs-on: ubuntu-latest
    steps:
      - uses: docker://agilepathway/pull-request-label-checker:latest
        with:
          prefix_mode: true
          any_of: "kind/"
          repo_token: ${{ secrets.GITHUB_TOKEN }}
